### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by mitsu-yama86** [mitsu-yama86/furima-32267#9]
#### フリマアプリのURL
https://furima-32267.herokuapp.com/

#### Basic認証のIDとパスワード
ymnmtj
2316

#### 出品者用のメールアドレスとパスワード
test@example
111aaa

#### 購入者用のメールアドレスとパスワード
aaa@aaa
111aaa

#### 購入用カードの番号・期限・セキュリティコード
4242424242424242
2/22
123

**Comment by oshim0115** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・ログイン時に他ユーザーの投稿した商品の編集ページURLを直接入力するとエラー画面に遷移してしまう（添付画像参照）
→こちらエラー画面を出さずトップページに遷移されるよう修正をお願いします。

・売却済み商品と同一の出品者アカウントでログインした状態で売却済み商品の編集ページURLを直接入力すると、そのまま編集ページに遷移してしまう。
→売却済み商品の場合、編集ページに遷移させず、トップページに遷移されるように修正をお願いします。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

<img width="596" alt="スクリーンショット 2021-01-06 17 46 36" src="https://user-images.githubusercontent.com/57244739/103748998-4034c680-5048-11eb-87c4-29484b338a99.png">

**Comment by sho0127** [comment]
mitsu-yama86さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
